### ISSUE TITLE
Everytime i use c.SetDashboard(context.TODO(), *board, sdk.SetDashboardParams, i am getting Templating init failed Cannot read property 'valueOf' of undefined

### ISSUE THREAD

**Issue by kittucandy** [grafana-tools/sdk#136] opened 2021-04-02 06:52 UTC
```
func main () {
	
        board := sdk.NewBoard("Sample dashboard title1234")
	board.ID = 1
	row1 := board.AddRow("Sample row title")
	row1.Add(sdk.NewGraph("Sample graph"))
	graph := sdk.NewGraph("Sample graph 2")
	target := sdk.Target{
		RefID:       "A",
		Datasource:  "Sample Source 1",
		Hide:        false,
		Measurement: "sample request 1"}
	graph.SetTarget(&target)
	row1.Add(graph)
	grafanaURL := "http://localhost:3000"
	c := sdk.NewClient(grafanaURL, "admin:xxxxx", sdk.DefaultHTTPClient)
	response, err := c.SetDashboard(context.TODO(), *board, sdk.SetDashboardParams{
		Overwrite: false,
	})
	if err != nil {
		fmt.Printf("error on uploading dashboard %s", board.Title)
	} else {
		fmt.Printf("dashboard URL: %v", grafanaURL+*response.URL)
	}
}```


dashboard is getting created but its giving the below error.  Need help on please

"Templating
Templating init failed Cannot read property 'valueOf' of undefined

An unexpected error happened
Details"

**Comment by kittucandy** [comment] 2021-04-02 06:52
![Uploading Screenshot 2021-04-02 at 12.06.26 PM.png…]()

**Comment by kittucandy** [comment] 2021-04-02 06:53
my datasource is Influx 2.0 and i am trying a flux query

**Comment by deepaksundar** [comment] 2021-04-02 10:44
@kittucandy 
It is failing because the time range for the dashboard is not set

try setting the time range for the dashboard as below

```board.Time.From = "now-30m"
board.Time.To = "now"```

**Comment by deepaksundar** [comment] 2021-04-02 10:54
https://github.com/grafana-tools/sdk/pull/137

**Comment by GiedriusS** [comment] 2021-04-02 15:02
Updated the example via #137. This is a duplicate of https://github.com/grafana-tools/sdk/issues/83. This is fixable from the sdk's end but it would involve lots of rework :( help needed!

**Closed by GiedriusS** 2021-04-02 15:02 UTC
